/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CustomSwipeList: typeof import('./components/CustomSwipeList.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    FormBuilder: typeof import('./components/FormBuilder.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    ProfileEdit: typeof import('./components/ProfileEdit.vue')['default']
    PropertySwitch: typeof import('./components/PropertySwitch.vue')['default']
    RenderMarkdown: typeof import('./components/RenderMarkdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwipeListItem: typeof import('./components/SwipeListItem.vue')['default']
    Winter: typeof import('./components/HomeScreenEffects/Winter.vue')['default']
  }
}
