/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[all]': RouteRecordInfo<'/[all]', '/:all', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/[id]/': RouteRecordInfo<'/admin/[id]/', '/admin/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/[id]/[all]': RouteRecordInfo<'/admin/[id]/[all]', '/admin/:id/:all', { id: ParamValue<true>, all: ParamValue<true> }, { id: ParamValue<false>, all: ParamValue<false> }>,
    '/admin/[id]/accounts': RouteRecordInfo<'/admin/[id]/accounts', '/admin/:id/accounts', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/[id]/bookings': RouteRecordInfo<'/admin/[id]/bookings', '/admin/:id/bookings', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/[id]/chat': RouteRecordInfo<'/admin/[id]/chat', '/admin/:id/chat', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/[id]/portal/guides': RouteRecordInfo<'/admin/[id]/portal/guides', '/admin/:id/portal/guides', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/[id]/property-settings': RouteRecordInfo<'/admin/[id]/property-settings', '/admin/:id/property-settings', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portal': RouteRecordInfo<'/portal', '/portal', Record<never, never>, Record<never, never>>,
    '/portal/[id]/': RouteRecordInfo<'/portal/[id]/', '/portal/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portal/[id]/gallery': RouteRecordInfo<'/portal/[id]/gallery', '/portal/:id/gallery', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portal/[id]/guides': RouteRecordInfo<'/portal/[id]/guides', '/portal/:id/guides', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portal/[id]/guides/[guide_id]': RouteRecordInfo<'/portal/[id]/guides/[guide_id]', '/portal/:id/guides/:guide_id', { id: ParamValue<true>, guide_id: ParamValue<true> }, { id: ParamValue<false>, guide_id: ParamValue<false> }>,
    '/portal/[id]/nearby': RouteRecordInfo<'/portal/[id]/nearby', '/portal/:id/nearby', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
